name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform support
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: servermanagerbot:${{ github.ref_name }}

      - name: Save Docker Image
        run: |
          docker save servermanagerbot:${{ github.ref_name }} | gzip > servermanagerbot-${{ github.ref_name }}.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: servermanagerbot-${{ github.ref_name }}
          path: servermanagerbot-${{ github.ref_name }}.tar.gz
          retention-days: 30
